modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/xEviLSpaWnx/TutorialTurtyWurty" #optional
[[mods]] #mandatory
modId="tutorialmod" #mandatory
version="1.15.2-1.0.0" #mandatory
displayName="Tutorial Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/xEviLSpaWnx/TutorialTurtyWurty" #optional
#logoFile="tutorialmod.png" #optional
credits="Thanks for this example mod goes to Turty Wurty from YouTube" #optional
authors="xXEviLSpaWnXx" #optional
description='''
Thanks to the tutorial on youtube from TurtyWurty.
'''
[[dependencies.tutorialmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
