modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/xEviLSpaWnx/TutorialTurtyWurty" #optional
[[mods]] #mandatory
modId="tutorial" #mandatory
version="1.5.1-1.0.0" #mandatory
displayName="Tutorial Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/xEviLSpaWnx/TutorialTurtyWurty" #optional
#logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Turty Wurty from YouTube" #optional
authors="xXEviLSpaWnXx" #optional
description='''
Thanks to the tutorial on youtube from TurtyWurty.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
